# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecchia <- function(log_range, locs, NNarray, num_threads, smoothness, compute_derivative) {
    .Call(`_GeoNonStat_vecchia`, log_range, locs, NNarray, num_threads, smoothness, compute_derivative)
}

derivative_sandwiches <- function(vecchia, left_vector, right_vector, NNarray, sauce_determinant_chef, num_threads) {
    .Call(`_GeoNonStat_derivative_sandwiches`, vecchia, left_vector, right_vector, NNarray, sauce_determinant_chef, num_threads)
}

matern_thingy_ <- function(mahala_dist, smoothness15) {
    .Call(`_GeoNonStat_matern_thingy_`, mahala_dist, smoothness15)
}

vecchia_ <- function(log_range, locs, NNarray, num_threads, smoothness, compute_derivative, result) {
    invisible(.Call(`_GeoNonStat_vecchia_`, log_range, locs, NNarray, num_threads, smoothness, compute_derivative, result))
}

derivative_sandwiches_ <- function(vecchia, left_vector, right_vector, NNarray, sauce_determinant_chef, num_threads) {
    .Call(`_GeoNonStat_derivative_sandwiches_`, vecchia, left_vector, right_vector, NNarray, sauce_determinant_chef, num_threads)
}

