# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nonstat_vecchia_Linv_col <- function(log_range, locs, NNarray, num_threads, smoothness, compute_derivative) {
    .Call(`_GeoNonStat_nonstat_vecchia_Linv_col`, log_range, locs, NNarray, num_threads, smoothness, compute_derivative)
}

log_determinant_derivative <- function(derivative, compressed_sparse_chol, NNarray) {
    .Call(`_GeoNonStat_log_determinant_derivative`, derivative, compressed_sparse_chol, NNarray)
}

